### ISSUE TITLE
GoLand 2022.2 crash

### ISSUE THREAD

**Issue by mojotx** [zt422680855/JsonEditor#5]
Cannot process toolwindow JSON Editor

com.intellij.diagnostic.PluginException: Cannot create class com.jsoneditor.JsonEditor (classloader=PluginClassLoader(plugin=PluginDescriptor(name=JSON Editor, id=com.zt.json-editor, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/Goland/ch-0/222.3345.118/GoLand.app.plugins/JsonEditor, version=2.2, package=null, isBundled=false), packagePrefix=null, instanceId=26, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:883)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:900)
	at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:113)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:248)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt:279)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:275)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:100)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:82)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private boolean javax.swing.tree.DefaultTreeCellRenderer.fillBackground accessible: module java.desktop does not "opens javax.swing.tree" to unnamed module @5cfccd82
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.intellij.util.ReflectionUtil.findFieldInHierarchy(ReflectionUtil.java:153)
	at com.intellij.util.ReflectionUtil.findAssignableField(ReflectionUtil.java:141)
	at com.intellij.util.ReflectionUtil.setField(ReflectionUtil.java:372)
	at com.intellij.ui.JBDefaultTreeCellRenderer.<init>(JBDefaultTreeCellRenderer.java:33)
	at com.intellij.ui.JBDefaultTreeCellRenderer.<init>(JBDefaultTreeCellRenderer.java:22)
	at com.jsoneditor.CustomTreeCellRenderer.<init>(CustomTreeCellRenderer.java:16)
	at com.jsoneditor.moddle.Right.initTree(Right.java:160)
	at com.jsoneditor.moddle.Right.paintRight(Right.java:136)
	at com.jsoneditor.moddle.Right.<init>(Right.java:115)
	at com.jsoneditor.JsonEditor.init(JsonEditor.java:43)
	at com.jsoneditor.JsonEditor.<init>(JsonEditor.java:37)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:844)
	... 17 more

**Comment by kgust** [comment]
This is not isolated to GoLand.  The following is from **PhpStorm 2022.2**. (Build #PS-222.3345.135, built on July 28, 2022)

>Cannot process toolwindow JSON Editor
>
>com.intellij.diagnostic.PluginException: Cannot create class com.jsoneditor.JsonEditor (classloader=PluginClassLoader(plugin=PluginDescriptor(name=JSON Editor, id=com.zt.json-editor, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PhpStorm2022.2/plugins/JsonEditor, version=2.2, package=null, isBundled=false), packagePrefix=null, instanceId=16, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:883)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:900)
	at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:113)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:248)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt:279)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:275)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:100)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:82)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private boolean javax.swing.tree.DefaultTreeCellRenderer.fillBackground accessible: module java.desktop does not "opens javax.swing.tree" to unnamed module @1dd5cc46
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.intellij.util.ReflectionUtil.findFieldInHierarchy(ReflectionUtil.java:153)
	at com.intellij.util.ReflectionUtil.findAssignableField(ReflectionUtil.java:141)
	at com.intellij.util.ReflectionUtil.setField(ReflectionUtil.java:372)
	at com.intellij.ui.JBDefaultTreeCellRenderer.<init>(JBDefaultTreeCellRenderer.java:33)
	at com.intellij.ui.JBDefaultTreeCellRenderer.<init>(JBDefaultTreeCellRenderer.java:22)
	at com.jsoneditor.CustomTreeCellRenderer.<init>(CustomTreeCellRenderer.java:16)
	at com.jsoneditor.moddle.Right.initTree(Right.java:160)
	at com.jsoneditor.moddle.Right.paintRight(Right.java:136)
	at com.jsoneditor.moddle.Right.<init>(Right.java:115)
	at com.jsoneditor.JsonEditor.init(JsonEditor.java:43)
	at com.jsoneditor.JsonEditor.<init>(JsonEditor.java:37)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:844)
	... 17 more
